steps:
- pwsh: '$(scriptsDirectory)/copy-typescript-models.ps1'
  displayName: 'Update models'
  env:
    BuildConfiguration: $(buildConfiguration)
    OutputFullPath: $(typewriterDirectory)/output
    RepoModelsDir: $(Build.SourcesDirectory)/msgraph-typescript-typings/
